name: Build
on:
  push: {}
jobs:
  run:
    runs-on: macOS-latest
    name: Build project
    steps:
    - uses: actions/checkout@master
    - name: Select latest Xcode
      run: sudo xcode-select --switch /Applications/Xcode_12_beta.app/Contents/Developer/
    - name: Build PreviewSystem
      run: ./PreviewSystem/build-script.sh
    - name: Upload PreviewSystem artifact
      uses: actions/upload-artifact@v2
      with:
        name: PreviewSystem
        path: PreviewSystem/distribution
    - name: Build CompileAPI
      run: swift build --package-path CompileAPI
    - name: Build Frontend
      working-directory: Frontend
      run: |
        ./scripts/install-dependency.sh
        npm install
        npm run build
    - name: Upload Frontend artifact
      uses: actions/upload-artifact@v2
      with:
        name: Frontend
        path: Frontend/dist