name: Build and deploy
on:
  push: {}
jobs:
  build:
    runs-on: macOS-latest
    name: Build project
    steps:
    - uses: actions/checkout@master
    - name: Select latest Xcode
      run: sudo xcode-select --switch /Applications/Xcode_12_beta.app/Contents/Developer/
    - name: Build PreviewSystem
      run: ./PreviewSystem/build-script.sh
    - name: Upload PreviewSystem artifact
      uses: actions/upload-artifact@v2
      with:
        name: PreviewSystem
        path: PreviewSystem/distribution
    - name: Build CompileAPI
      run: swift build --package-path CompileAPI
    - name: Build Frontend
      working-directory: Frontend
      run: |
        apt install -y wabt binaryen
        npm install
        npm run build:prod
    - name: Upload Frontend artifact
      uses: actions/upload-artifact@v2
      with:
        name: Frontend
        path: Frontend/dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: Deploy artifacts
    steps:
    - name: Download Frontend artifact
      uses: actions/download-artifact@v2
      with:
        name: Frontend
    - name: Deploy to Netlify
      run: |
        npx netlify-cli deploy --dir=./Frontend
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  build-frontend-docker-image:
    runs-on: ubuntu-latest
    name: Build Frontend Docker image
    steps:
    - uses: actions/checkout@master
    - name: Build Frontend image
      run: docker build -f docker/Frontend/Dockerfile .
  build-compile-api-docker-image:
    runs-on: ubuntu-latest
    name: Build CompileAPI Docker image
    steps:
    - uses: actions/checkout@master
    - name: Build CompileAPI image
      run: docker build -f docker/CompileAPI/Dockerfile .
